#! /bin/bash
#SBATCH --job-name=ATS
#SBATCH --partition=lr6
#SBATCH --qos lr_debug
#SBATCH --qos condo_farea
#SBATCH --ntasks=1
#SBATCH -t 0:30:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=laeguiguren@lbl.gov
#SBATCH --account=lr_farea
#SBATCH --output=ats%jodid.out
#SBATCH --error=ats%jodid.err
module purge
module load gcc/9.2.0
module load openmpi/4.0.1-gcc
module load gcc-9.2.0/lapack/3.9.0
mpirun -np 1 /global/home/groups-sw/pc_ideas/amanzi-master3/install/bin/amanzi --xml_file="farea-crunch_t.xml" > out.log

